### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by wscraper** [rmax/dirbot-mysql#5]
scrapy list
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scrapy/cmdline.py", line 108, in execute
    settings = get_project_settings()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scrapy/utils/project.py", line 60, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scrapy/settings/**init**.py", line 285, in setmodule
    self.set(key, getattr(module, key), priority)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scrapy/settings/**init**.py", line 260, in set
    self.attributes[name].set(value, priority)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scrapy/settings/**init**.py", line 55, in set
    value = BaseSettings(value, priority=priority)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scrapy/settings/**init**.py", line 91, in **init**
    self.update(values, priority)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scrapy/settings/**init**.py", line 317, in update
    for name, value in six.iteritems(values):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/six.py", line 581, in iteritems
    return iter(d.items(**kw))
AttributeError: 'list' object has no attribute 'items'

**Comment by hendisantika** [comment]
# Same error with mine.

Traceback (most recent call last):
  File "/home/hendisantika/Documents/python/ENV/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/cmdline.py", line 108, in execute
    settings = get_project_settings()
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/utils/project.py", line 68, in get_project_settings
    settings.setmodule(settings_module_path, priority='project')
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/settings/**init**.py", line 285, in setmodule
    self.set(key, getattr(module, key), priority)
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/settings/**init**.py", line 260, in set
    self.attributes[name].set(value, priority)
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/settings/**init**.py", line 55, in set
    value = BaseSettings(value, priority=priority)
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/settings/**init**.py", line 91, in **init**
    self.update(values, priority)
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/scrapy/settings/**init**.py", line 317, in update
    for name, value in six.iteritems(values):
  File "/home/hendisantika/Documents/python/ENV/local/lib/python2.7/site-packages/six.py", line 599, in iteritems
    return d.iteritems(**kw)
AttributeError: 'list' object has no attribute 'iteritems'

# 

Any advice?

Thanks

**Comment by JohnSell620** [comment]
Give this a try. In settings.py, change the ITEM_PIPELINES:
`ITEM_PIPELINES = {`
`'dirtbot.pipelines.FilterWordsPipeline': 400,`
`'dirtbot.pipelines.RequiredFieldsPipeline': 600,`
`'dirtbot.pipelines.MySQLStorePipeline': 800,`
`}`.
Helpful post:
https://stackoverflow.com/questions/37442907/scrapy-attributeerror-list-object-has-no-attribute-iteritems
